M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date 2024. jan. 16., kedd, 21:13:50 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-16T21:13:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X14.975Y13.5
M30
